# Default values for AWS Exporter

image:
  repository: asserts/aws-cloudwatch-exporter
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag:

service:
  aws:
    port: 8010
  # jmx:
  #   port: 8095

# Ingress configuration
ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: aws-exporter.example.com
      paths:
        - /
  # -- TLS configuration for the api-server ingress
  tls:
    - secretName: aws-exporter-tls
      hosts:
        - aws-exporter.example.com

env:
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""

serviceMonitor:
  enabled: false
  endpoints:
    - port: aws
      path: /aws-exporter/actuator/prometheus
    # - port: jmx

serviceAccount:
  create: false
