scrape_configs:
  - job_name: 'ecs-service-discovery'
    honor_labels: true
    file_sd_configs:
      - files:
          - '/opt/asserts/ecs-scrape-targets.yml'
  - job_name: 'ecs-service-discovery-https'
    honor_labels: true
    scheme: https
    tls_config:
      insecure_skip_verify: %{SKIP_TLS_VERIFY}
    file_sd_configs:
      - files:
          - '/opt/asserts/ecs-scrape-targets-https.yml'
