scrape_configs:
  - job_name: 'agent'
    static_configs:
      - targets: [ 'localhost:8429' ]
  - job_name: 'ecs-service-discovery'
    honor_labels: true
    file_sd_configs:
      - files:
          - '/opt/asserts/ecs-scrape-targets.yml'
