regions:
  - us-west-2
namespaces:
  - name: lambda
    scrapeInterval: 60
    period: 60
    dimensionFilters:
      FunctionName: (.+)
    metrics:
      - name: Invocations
        stats:
          - Sum
      - name: Errors
        stats:
          - Sum
      - name: DeadLetterErrors
        stats:
          - Sum
      - name: Throttles
        stats:
          - Sum
      - name: DestinationDeliveryFailures
        stats:
          - Sum
      - name: Duration
        stats:
          - p99
          - Average
      - name: ConcurrentExecutions
        stats:
          - Maximum
    logs:
      - lambdaFunctionName: Function.+
        logFilterPattern: "About to put message in SQS Queue"
        regexPattern: ".*put message in SQS Queue https://sqs.us-west-2.amazonaws.com/342994379019/(.+)"
        labels:
          "destination_type": "SQSQueue"
          "destination_name": "$1"
  - name: sqs
    metrics:
      - name: NumberOfMessagesReceived
        stats:
          - Sum
      - name: NumberOfMessagesSent
        stats:
          - Sum
  - name: dynamodb
    metrics:
      - name: ConsumedReadCapacityUnits
        stats:
          - Maximum
          - Average
      - name: ConsumedWriteCapacityUnits
        stats:
          - Maximum
          - Average
      - name: ProvisionedReadCapacityUnits
        stats:
          - Average
      - name: ProvisionedWriteCapacityUnits
        stats:
          - Average
      - name: ReadThrottleEvents
        stats:
          - Sum
      - name: WriteThrottleEvents
        stats:
          - Sum
  - name: s3
    period: 86400
    scrapeInterval: 86400
    metrics:
      - name: NumberOfObjects
        stats:
          - Average
      - name: BucketSizeBytes
        stats:
          - Average
  - name: lambdainsights
    scrapeInterval: 60
    period: 60
    dimensionFilters:
      FunctionName: (.+)
    metrics:
      - name: memory_utilization
        stats:
          - Average
      - name: total_memory
        stats:
          - Average
      - name: used_memory_max
        stats:
          - Average
      - name: cpu_total_time
        stats:
          - Sum
      - name: tx_bytes
        stats:
          - Sum
      - name: rx_bytes
        stats:
          - Sum