version: '3'
services:
  aws-cloudwatch-exporter:
    build:
      context: .
      dockerfile: Dockerfile
    image: asserts/aws-cloudwatch-exporter:latest
    ports:
      - "8010:8010"
    env_file:
      - env.properties
    volumes:
      - "./opt/asserts:/opt/asserts"
  aws-integration-agent:
    build:
      context: .
      dockerfile: Dockerfile.agent
    image: asserts/aws-integration-agent:v0.0.14
    ports:
      - "8014:8014"
    env_file:
      - env_agent.properties
