apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-exporter
  namespace: {{ .Release.Namespace }}
  labels:
    app: aws-exporter
spec:
  selector:
    matchLabels:
      app: aws-exporter
  replicas: 1
  template:
    metadata:
      labels:
        app: aws-exporter
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        name: {{ .Chart.Name }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
          limits:
            memory: 4Gi
          requests:
            memory: 4Gi
        ports:
          - name: aws
            containerPort: {{ .Values.service.aws.port }}
            protocol: TCP
          - name: jmx
            containerPort: {{ .Values.service.jmx.port }}
            protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: jmx
        readinessProbe:
          httpGet:
            path: /
            port: jmx
        {{- if .Values.env }}
        env:
        {{- range $key, $val := .Values.env }}
        - name: {{ $key }}
          value: {{ $val | quote }}
        {{- end }}
        {{- end }}
