apiVersion: v1
kind: Service
metadata:
  name: {{ include "aws-exporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aws-exporter.labels" . | nindent 4 }}
spec:
type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.aws.port }}
      targetPort: {{ .Values.service.aws.port }}
      protocol: TCP
      name: aws
  selector:
    app: aws-exporter
