---
- name: deploy cloudwatch exporter
  hosts: "localhost"
  become: true
  become_user: root
  vars:
    hosts: localhost
  pre_tasks:
  roles:
    - role: ansible-role-java
      java_packages:
        - openjdk-8-jdk
    - role: ansible-vmagent
      vmagent_global:
        scrape_interval: 60s
        scrape_timeout: 30s
      vmagent_scrape_configs:
        - job_name: vmagent
          static_configs:
          - targets:
            - localhost:8429
        - job_name: aws-exporter
          metrics_path: '/aws-exporter/actuator/prometheus'
          static_configs:
          - targets:
            - localhost:8010    
  post_tasks:
    - name: Install package
      apt:
        name: "{{ item }}"
      with_items:
        - awscli
        - unzip
    - name: "Pull artifacts from S3"
      command: "aws s3 cp --only-show-errors s3://test-vmbackupmanager/latest/aws-exporter-21.11.0.22e7832.zip /home/ubuntu/aws-exporter/"

    - name: Extract overpass aws exporter tar.gz into /aws-exporter/
      unarchive:
        src: "/home/ubuntu/aws-exporter/aws-exporter-21.11.0.22e7832.zip"
        dest: "/home/ubuntu/aws-exporter/"
        remote_src: yes

    - name: Run the exporter
      shell: |
        cd aws-exporter-21.11.0.22e7832/
        cp conf/cloudwatch_scrape_config_sample.yml .
        mv cloudwatch_scrape_config_sample.yml cloudwatch_scrape_config.yml
        bin/aws-exporter &
        exit 0
